require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "scripts/**/*"

Style/AsciiComments:  
  Enabled: true  
    
Style/Documentation:  
  Enabled: true  
  Exclude:  
    - "spec/**/*"  
    - "test/**/*"  
    - "db/migrate/*"  
    - "config/**/*"

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Bundler/GemComment:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "db/migrate/*"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
  Max: 15

Layout/LineLength:
  Max: 95

Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"

Rails/LexicallyScopedActionFilter:
  Exclude:
    - "app/controllers/**/*_controller.rb"
