version: "3"

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: bin/server
    volumes:
      - .:/doctour
    ports:
      - "3000:3000"
    depends_on:
      - db
      - prod_exporter
    env_file:
      - .env
    environment:
      - PROMETHEUS_EXPORTER_HOST=prod_exporter
      - PROMETHEUS_EXPORTER_PORT=9394
      - PUMA_WORKERS=1

  prod_exporter:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "9394:9394"
    env_file:
      - .env
    volumes:
      - .:/doctour
    command: bundle exec prometheus_exporter -b 0.0.0.0 -p 9394 --prefix 'doctour_'
