version: "3"

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: bin/server
    volumes:
      - .:/doctour
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
