# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  # adapter: postgresql
  # encoding: unicode
  # host: doctourdbfree.ctbnspuq26es.us-east-2.rds.amazonaws.com
  # port: 5432
  # username: postgres
  # password: 30271255
  # url: 'postgresql://postgres:30271255@doctourdbfree.ctbnspuq26es.us-east-2.rds.amazonaws.com/doctourdbfree'
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  host: database-dev.ctbnspuq26es.us-east-2.rds.amazonaws.com
  port: 5432
  username: postgres
  password: 30271255
  url: 'postgresql://postgres:30271255@database-dev.ctbnspuq26es.us-east-2.rds.amazonaws.com/doctour'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: database-dev.ctbnspuq26es.us-east-2.rds.amazonaws.com
  port: 5432
  username: postgres
  password: 30271255
  url: 'postgresql://postgres:30271255@database-dev.ctbnspuq26es.us-east-2.rds.amazonaws.com/doctour'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: doctourdbfree

production:
  database: d8052m390lsdmb
  timeout: 5000
  uri: postgres://xpgkmgcuvejnui:2fe42fc7977571bf5f72644839a0b4714031578aa438204966bb490977045c34@ec2-54-144-196-35.compute-1.amazonaws.com:5432/d8052m390lsdmb
  username: xpgkmgcuvejnui
  password: 2fe42fc7977571bf5f72644839a0b4714031578aa438204966bb490977045c34
  port: 5432
  host: ec2-54-144-196-35.compute-1.amazonaws.com

